name: wfto_change_agent
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^1.1.7+2
  path_provider: ^1.4.2
  curved_navigation_bar: ^0.3.1
  simple_animations: ^1.3.4
  bubble_bottom_bar: ^1.2.0
  flutter_platform_widgets: ^0.20.2
  keyboard_visibility: ^0.5.6
  intl: ^0.16.0

  cloud_firestore: ^0.12.10
  firebase_auth: ^0.14.0+9
  firebase_core: ^0.4.1+5
  google_sign_in: ^4.0.14
  font_awesome_flutter: ^8.5.0
  rxdart: ^0.22.6

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/ocj_splash.png
    - assets/images/fidelitech_logo-cutout.png
    - assets/images/10.jpeg
    - assets/images/9.jpeg
    - assets/images/8.jpeg
    - assets/images/7.jpeg
    - assets/images/6.jpeg
    - assets/images/5.jpeg
    - assets/images/4.jpeg
    - assets/images/3.jpeg
    - assets/images/2.jpeg
    - assets/images/1.jpeg
    - assets/images/ocj_logo_black.png
    - assets/images/ocj_logo_color.png
    - assets/images/ocj_logo_white.png
    - assets/images/ocj_logo_colored_bg.png
    - assets/images/insta.png
    - assets/images/twitter.png
    - assets/images/facebook_logo.png
    - assets/images/connect.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito/Nunito-Black.ttf
          weight: 700
        - asset: assets/fonts/Nunito/Nunito-BlackItalic.ttf
          weight: 700
        - asset: assets/fonts/Nunito/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito/Nunito-BoldItalic.ttf
          weight: 700
        - asset: assets/fonts/Nunito/Nunito-ExtraBold.ttf
          weight: 700
        - asset: assets/fonts/Nunito/Nunito-ExtraBoldItalic.ttf
          weight: 700
        - asset: assets/fonts/Nunito/Nunito-ExtraLight.ttf
          weight: 700
        - asset: assets/fonts/Nunito/Nunito-ExtraLightItalic.ttf
          weight: 700
        - asset: assets/fonts/Nunito/Nunito-Italic.ttf
          weight: 700
        - asset: assets/fonts/Nunito/Nunito-Light.ttf
          weight: 700
        - asset: assets/fonts/Nunito/Nunito-Regular.ttf
          weight: 700
        - asset: assets/fonts/Nunito/Nunito-SemiBold.ttf
          weight: 700

    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand/Quicksand-Bold.ttf
          weight: 700
        - asset: assets/fonts/Quicksand/Quicksand-Light.ttf
          weight: 100
        - asset: assets/fonts/Quicksand/Quicksand-Medium.ttf
          weight: 200
        - asset: assets/fonts/Quicksand/Quicksand-Regular.ttf
          weight: 400
        - asset: assets/fonts/Quicksand/Quicksand-SemiBold.ttf
          weight: 600

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
